spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/oauth2
    username: root
    password: root
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: /login/oauth2/code/google
            scope:
              - email
              - profile
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html